apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nextflow
    component: scheduler
    tier: control-plane
  name: workflow-scheduler
spec:
  nodeSelector: 
    ftschirpkespecial: scheduler
  containers:
  - env:
    - name: spring_profiles_active
      value: dev
    - name: SCHEDULER_NAME
      value: workflow-scheduler
    - name: AUTOCLOSE
      value: "false"
    image: fabianlehmann/test1:sch_vtestNoGroup
    # image: commonworkflowscheduler/kubernetesscheduler:2.0
    imagePullPolicy: IfNotPresent
    name: workflow-scheduler
    resources:
      requests:
        cpu: "1"
        memory: 2000Mi
    volumeMounts:
    - mountPath: /input
      name: data
  securityContext:
    runAsUser: 0
  serviceAccount: cwsscheduleraccount-ftschirpke
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: ceph-data
